name: CarbonCopy Node.js Backend - Build Docker Image and upload to GCR

on:
  workflow_run:
    workflows:
      - "Run Jest Unit Tests"
    types:
      - completed

jobs:
  build_and_push_to_gcr:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      IMAGE_NAME: carboncopy-backend
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet

      - name: Build the docker image
        run: docker build . -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME

      - name: Push the docker image to Container Registry (GCR)
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:latest