name: CarbonCopy Node.js Backend - Run Jest Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
      - name: Installing dependencies
        run: npm ci
      - name: Executing tests
        run: npm test